### ISSUE TITLE
Pokemon-Multiform 

### ISSUE THREAD

**Issue by Terratroid** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#152] opened 2021-08-27 13:33 UTC
Pokemon with mulitple forms, regional varients don't generate upon drag and drop and return an error.
Uncaught (in promise) TypeError: Cannot read property 'number' of null
    at ActorGenerator.PrepareEvolution (actor-generator.js:162)
    at ActorGenerator.Generate (actor-generator.js:80)
    at Function.Create (actor-generator.js:129)
    at async Object.FinishDexDragPokemonCreation (species-command-parser.js:184)

**Comment by dylanpiera** [comment] 2021-09-05 14:51
I tried to reproduce the issue but was unable to with the exception of Darmanitan-normal. 

What version of PTU & Foundry are you using?

**Comment by SoraHjort** [comment] 2021-09-05 22:15
Found a solution, it appears the check on forms is backwards, or it's not overwriting values properly.

.\Data\systems\ptu\module\utils\species-command-parser.js
lines 82 through 105

The first and third ` if(result.status === 404) {` blocks need to be swapped. So that the text name check comes first.

Basically the whole block starting at 82 and ending at 105 needs to be

```
export async function GetSpeciesArt(mon, imgDirectoryPath, type = ".png", shiny = false) {
    const basePath = imgDirectoryPath+(imgDirectoryPath.endsWith('/') ? '' : '/')

    const shiny_path = shiny ? "s" : "";

    let path = basePath+lpad(mon?.number, 4)+shiny_path+type;
    let result = await fetch(path);
    if(result.status === 404) {
        path = basePath+mon?._id?.toLowerCase()+shiny_path+type;
        result = await fetch(path);
    }
    if(result.status === 404) {
        path = basePath+mon?._id+shiny_path+type;
        result = await fetch(path);
    }
    if(result.status === 404 && mon?.number < 1000) {
        path = basePath+lpad(mon?.number, 3)+shiny_path+type;
        result = await fetch(path);
    }
    if(result.status === 404) {
        return undefined;
    }
    return path;
}
```

Honestly, with the way it's written, I would have thought the form check would overwrite the first true. But for some reason it isn't doing it here. It still performs the check regardless, just, not updating the value after the first.

Had a friend GMing a PTU game come to me about having this issue, and after digging around found that this was at the very least, a solution. Whether or not it's representative of a larger problem or if this was all of what the problem was, I'm not to say.

But in our tests it's solved the problem on both our ends. So, hopefully this'll help solve the problem for everyone. Or atleast give people a way to do a work around till the problem has been identified, if it goes beyond that block.

Hope this helps you out.

**Comment by dylanpiera** [comment] 2021-09-06 07:20
@SoraHjort I must say I'm a little confused what your solution is supposed to be fixing?

This issue has been fixed in the latest Beta (V8). Regional/Sub forms their art depends on how you have setup your images.

**Closed** 2022-02-28 17:24 UTC
Labels: bug
