### ISSUE TITLE
Badly Poisoned and Bad Sleep not working as intended

### ISSUE THREAD

**Issue by joosh98** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#259] opened 2022-11-21 20:40 UTC
Badly Poisoned - damage does not scale correctly:

_When Badly Poisoned, the afflicted instead loses 5 Hit Points; this amount is doubled each consecutive round (10, 20, 40, etc)_

Bad Sleep - does not trigger a d20 DC16 save check at the end of the turn:

_Whenever the user makes a Save Check to save against Sleep, they lose two ticks of Hit Points._ 

_At the end of the sleeper’s turns, they may make a DC 16 Save Check to wake up._

**Comment by dylanpiera** [comment] 2022-12-24 07:52
Can't reproduce this in my local. Likely fixed by updating the foundry v10 compatibility

**Closed by dylanpiera** 2022-12-24 07:52 UTC
Labels: v3-Bug, P2
